### ISSUE TITLE
[0.5d] Wat is de definitie / datastandaard van DAMO en HyDAMO

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [threedi/hhnk-threedi-tools#114]

**Comment by DanielTollenaar** [comment]
Zie: https://github.com/HetWaterschapshuis/HyDAMOValidatieModule/blob/main/hydamo_validation/schemas/hydamo/HyDAMO_2.3.json

"minItems": 1 maakt iets verplicht "uniqueItems" : true maakt dat elke record een unieke waarde moet bevatten t.o.v. andere records in dezelfde colom

**Comment by Overmeen** [comment]
Ik heb het volgende gevonden op https://nhi.nu/ontwikkelingen/hydamo/:

Ten eerste een beschrijving van het datamodel, waarin alle objecten en attributen worden toegelicht en waarin wordt aangegeven welke onderdelen uit DAMO komen en welke er zijn toegevoegd. De huidige versie is v12. Op basis van gebruikerswensen is er per 1 maart 2021 een v13 gereed gekomen. Deze nieuwe versie zal de basis gaan vormen voor de validatietool die in 2021 gebouwd gaat worden en voor modelgeneratoren zoals D-HyDAMO.  [DOWNLOAD DATAMODEL (v12)](https://github.com/helpdeskNHI/nhi/raw/master/datamodel/datamodel_v12.xlsx) of [DOWNLOAD DATAMODEL (v13)](https://github.com/helpdeskNHI/nhi/raw/master/datamodel/HyDAMO_datamodel_v13.xlsx)

Ten tweede de twee schema's (.xsd) om te weten waar de .gml bestanden aan moeten voldoen. De .gml bestanden worden per Object (Stuw, HydroObject, Doorstroomopening enz.) aangemaakt en zijn het [standaard](https://nl.wikipedia.org/wiki/Geography_Markup_Language) uitwisselformaat voor de HyDAMO data.
DOWNLOAD nhiFeatureTypes.xsd en sharedTypes.xsd [hier](https://github.com/helpdeskNHI/nhi/tree/master/schema) en kies voor versie12 of versie13.

**Comment by leendertvanwolfswinkel** [comment]
Het beheer van deze datastandaard laat wel wat te wensen over, dat is wel duidelijk. Maar je voorstel lijkt me goed!

Dit is een belangrijke ontwerpkeuze, dus dit ook graag openemen in de devdocs
