### ISSUE TITLE
Welke DAMO versie wordt gebruikt in de domeinlijsten van CSO?

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [threedi/hhnk-threedi-tools#126]
DAMO bevat integer Enums. HyDAMO gebruikt strings. CSO heeft ook een value mapping voor deze Enums. Het is onbekend of dit overeenkomt met de HyDAMO value mapping / welke versie van de DAMO domeintabellen wordt gebruikt. Er moet uitgezocht worden hoe dit precies zit, zodat we weten of we CSO

**Comment by wvanesse** [comment]
CSO maakt gebruikt van de domeintabellen uit DAMO 2.4 (bij het opnemen naar de STAGING-laag worden domeinwaarden overgenomen en wordt de domeinomschrijving als extra veld opgenomen; beide velden worden doorgezet naar de lagen in het CS_OBJECTEN-schema).

Maar een beperkt deel van DAMO is in CSO opgenomen. O.a. de hydroobjecten zijn niet opgenomen. 

In de BI-rapportage van CS-Objecten ([CS Objecten MDS - Power BI](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.powerbi.com%2Fgroups%2Fme%2Freports%2F87d51081-3a44-41c1-a14b-bb8c08df930b%2FReportSectione72ee4a7ee025122a2b7%3Fctid%3Dd2e6706d-08b5-4123-bea1-186399f9d47f%26experience%3Dpower-bi&data=05%7C02%7Cw.vanesse%40hhnk.nl%7Cfc1a7569a2424e59190d08dd0a3a38b7%7Cd2e6706d08b54123bea1186399f9d47f%7C0%7C0%7C638677967354419439%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=rxjBISDadJ%2BtlMG%2BHQhrjR1%2FS9HcvTdswnTryWeerdc%3D&reserved=0)) onder het tabblad meldingen (links te kiezen) 
Zie je onder soort objecten de verschillende objecten die opgenomen zijn in CSO.

Als je de data uit CS Objecten in het GIS wilt zien:
Op onderstaande plek staat een databaseconnectie:
G:\03_Applicaties\08_ArcGIS\Connectionfiles\CSOPRD_LEES@ODSPRD .sde
