### ISSUE TITLE
issue bij modelsplitter: als het model not valid is (fout in schematisatie), krijg je geen model id terug.

### ISSUE THREAD

**Issue by wvanesse** [threedi/hhnk-threedi-tools#17]
Zie foutmelding:
![Image](https://user-images.githubusercontent.com/48908991/225005948-da79f365-ccaf-41c5-873e-1c18bf5d375a.PNG)

**Comment by jkaptein** [comment]
sqlite check voor uploaden

**Comment by d2hydro** [comment]
Wat we gaan oppakken:
- [ ] gebruiker kan alleen uploaden als dataverificatie is uitgevoerd
- [ ] controle op fouten na dataverificatie. @wvangerwen; willen/kunnen we hard teste of er wel/geen fouten in een model zitten in het model na verificatie?
- [ ] data verificatie bereikbaar vanuit model splitter

**Comment by wvanesse** [comment]
Wat is dataverificatie?

Bedoel je de sqlite check of de schematisation checker van N&S? Die laatste is inmiddels misschien wel completer. 

Het lijkt me goed een check uit te voeren omdat we daarmee ook een fout uit de model settings tackelen. Wel duurt het dan wat langer.

**Comment by d2hydro** [comment]
@wvanesse en @wvangerwen; deze linker-kolom bevat alle data verificatie (zie plaatje hieronder); we zouden:
- [ ] alle subselecties onder data verificatie en eenmalige tests weg laten; houden we dus maar 2 opties over; dataverificatie en eenmalige tests
- [ ] data verificatie verplicht maken voor upload zoals hierboven beschreven

Wat is NenS schematisation checker en (waar) moet deze worden toegevoegd?

![Image](https://github.com/threedi/hhnk-threedi-tools/assets/43996424/72814cd4-03ec-44bf-b76d-a264ad83b54d)

**Comment by d2hydro** [comment]
Deze issue wordt hier opgelost: https://github.com/threedi/hhnk-threedi-plugin/issues/107
