### ISSUE TITLE
actions sneller maken

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-tools#19]
Poging om de actions sneller te maken met conda-lock file. 

https://github.com/conda-incubator/setup-miniconda/blob/v2.0.0/README.md#example-7-explicit-specification

Lijkt nu wel te initialiseren, nog steeds erg traag. Maar vervolgens loopt ie bij de testen nog ergens tegenaan. In deze branch [unitest-codecov](https://github.com/threedi/hhnk-threedi-tools/tree/unitest-codecov)

https://github.com/threedi/hhnk-threedi-tools/actions/runs/4554881417 

Hoe verder.

**Comment by d2hydro** [comment]
- [ ] upload naar code-cov toevoegen
- [ ] cov-badge in index.md readme.md
