### ISSUE TITLE
HHTPerror bij downloaden van rasters 

### ISSUE THREAD

**Issue by Ckerklaan** [threedi/hhnk-threedi-tools#2]
HTTPError Traceback (most recent call last)
g:\02_Werkplaatsen\06_HYD\Projecten\HKC20004 Gevoeligheidsanalyse compenserendebergingstool\06. Afgeleide gegevens\01_waterstandstijging\00_scripts\01_CBT_download_netcdf.py in
93 pathname = pathname,
94 is_threedi_scenario = True,
---> 95 export_task_csv=export_task_csv)

C:\ProgramData\Anaconda3\envs\threedipy\lib\site-packages\threedi_scenario_downloader\downloader.py in download_raster(scenario, raster_code, target_srs, resolution, bounds, bounds_srs, time, pathname, is_threedi_scenario, export_task_csv)
383 logging.debug(
384 "Task succeeded, start downloading url: {}".format(
--> 385 get_task_download_url(task_uuid)
386 )
387 )

C:\ProgramData\Anaconda3\envs\threedipy\lib\site-packages\threedi_scenario_downloader\downloader.py in get_task_download_url(task_uuid)
204 url = "{}tasks/{}/".format(LIZARD_URL, task_uuid)
205 r = requests.get(url=url, auth=("key", get_api_key()))
--> 206 r.raise_for_status()
207 return r.json()["result_url"]
208 # What to do if task is not a success?

C:\ProgramData\Anaconda3\envs\threedipy\lib\site-packages\requests\models.py in raise_for_status(self)
941
942 if http_error_msg:
--> 943 raise HTTPError(http_error_msg, response=self)
944
945 def close(self):

HTTPError: 503 Server Error: Service Unavailable for url: https://demo.lizard.net/api/v3/tasks/ef7222a5-b4b4-4a67-90c9-10818497d83e/

**Comment by wvangerwen** [comment]
stale, alot has changed in the meantime
