### ISSUE TITLE
PROJ

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-tools#20]
Krijg een foutmelding door de installatie van postgres. 
```CPLE_AppDefinedError: PROJ: proj_identify: D:\postgres152\share\contrib\postgis-3.3\proj\proj.db contains DATABASE.LAYOUT.VERSION.MINOR = 0 whereas a number >= 2 is expected. It comes from another PROJ installation.```

In system variables staat PROJ_LIB=D:\postgres152\share\contrib\postgis-3.3\proj gedefineerd. Nu weg gehaald, kijken of dit effect heeft op datachecker.
https://stackoverflow.com/questions/71460405/gdal-in-virtual-environment-vs-postgressql-11

![image](https://user-images.githubusercontent.com/41104904/230139212-09d5eb87-fe5d-41e4-8fb4-16f008942c3b.png)

**Comment by d2hydro** [comment]
Better safe then sorry; de PROJ_LIB variabele wordt nu gezet in de app, zodat hij beschikbaar is voor de ap:

![image](https://user-images.githubusercontent.com/43996424/230336845-47319c78-8bd1-4d24-ba75-b46291cc4240.png)
