### ISSUE TITLE
calculation_gui custom rain verwijzing mappen

### ISSUE THREAD

**Issue by jkaptein** [threedi/hhnk-threedi-tools#57]
custom rain button --> juiste verwijzing naar mappen

**Comment by wvangerwen** [comment]
kan je dit nog reproduceren en beter beschrijven wat er mis gaat?

**Comment by d2hydro** [comment]
**Reproductie:**
- Open M.I. en 3Di plugin
- selecteer htt.model_test
- open Jupyter Notebook Server
- open `01_calculation_gui.ipynb`
- selecteer model
- selecteer custom rain, vul de parameters in
- druk op create simulation
**Resultaat:**
![Image](https://github.com/threedi/hhnk-threedi-tools/assets/43996424/ea4c09a8-901f-4b83-baf0-1bcf3814a7bc)

**Fixen:**
- [ ] error in mkdir
- [ ] grootte invulschermen custom_rain parameters vs labels ervoor
