### ISSUE TITLE
defaults values (k-max/grid space) in model settings

### ISSUE THREAD

**Issue by wvanesse** [threedi/hhnk-threedi-tools#60]
waarom staat er gridspace en 12 en kmax 4 in de model settings? Dit is niet de default voor de meeste bwn modellen en daarom extra verwarrend als dit wel uit de modelsplitter rolt. Is het misschien goed om een melding te geven als deze instellingen in de model settings excel en de global settings in de sqlite niet gelijk zijn?

![image](https://github.com/threedi/hhnk-threedi-tools/assets/48908991/b0887fdc-9db9-4647-b393-3c4f56c4cc3b)

**Comment by jcacosta89** [comment]
- [ ] We kunnen een test doen om de Global Setting tabel te controleren. Deze test moet kmax en grid_space bevatten
- [ ]  We kunnen ook dat binnen model splitter doen. Dat betekent dat we een test voor de Excel tabellen moeten doen. Welke optie denken jullie beter is?

**Comment by wvanesse** [comment]
Ik zou bij de model splitter logisch vinden. Daar is al een feedback venster, het lijkt me horen bij de feedback van de splitter. Bovendien pas ik de xlsx vaak pas aan nadat ik de sqlite tests doe.

**Comment by wvangerwen** [comment]
fixed in #65
