### ISSUE TITLE
sneller maken ClimateResult

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-tools#74]
Het initializeren van deze class in htt duurde nogal lang in het load_layers deel.

Hierdoor een en ander omgebouwd zodat niet alles altijd wordt ingelezen bij eerste initialisatie. Maar.. nu heeft ie problemen met getattr bij download_gui_class.py 
`output_folder = getattr(self.vars.batch_fd.downloads, row["dl_name"]).netcdf`

Staan FIXME's in de code van download_gui_class.py en test_folder_structure.py

Voorlopig alleen op branch [layer-structure-qgis](https://github.com/threedi/hhnk-threedi-tools/tree/layer-structure-qgis)

**Comment by d2hydro** [comment]
fixed in #76
