### ISSUE TITLE
Start gui werkt niet meer out of the box

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-tools#9]
Nu is dit notebook_data.json bestand nodig.

![image](https://user-images.githubusercontent.com/41104904/145173970-29d18077-abd9-4896-ab16-6b569f42e7c6.png)

En in de hhnk-plugin mag ik de jupyter notebooks niet aanmaken zonder een polderfolder te hebben die ook nog eens de juiste mappen bevat.

**Comment by Ckerklaan** [comment]
@wvangerwen Kunnen we er geen vereiste van maken dat je wel een folder moet aanmaken? Dan komen de downloads ook gelijk in dezelfde structuur.

**Comment by wvangerwen** [comment]
@Ckerklaan dat is in principe geen slecht plan. Heb dat ook getest, maar toen direct foutmelding dat die de sqlite niet had. Waardoor het klimaatscenarios tabblad uitgegrijsd bleef en ik de notebooks dus niet kon openen. 
Na toevoegen sqlite wel doorheen gekomen. Deze staat echter op een andere schijf dus moet iets hebben om de notebook server te openen terwijl die naar de juiste map kijkt.
